class Map:
    Locators= dict(App='//a[@id="link-create"]',started='//button[text()="Let\'s get started!"]',newpagebutton='//a[@id="add-page"]',
      Messaging='(//h3[@class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-top ui-corner-all"])[3]',
      sms='//*[@id=\"accordion\"]/div[4]/ul/li[3]',window='//div[@id="tabs-1"]',
      newpage='//li[@class="ui-tab-left"]//a', newpagetxt='//input[@class="indented submitonenter"]',
      Create='(//button[text()="Create"])[2]', mainpage='//div[@id="tabs-2"]', 
      conector="//div[@id='module-1']/div/div[@class='syn-node ui-draggable syn-node-active']",
      connectorsms="//div[@id='module-2']/div/div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']", 
      messagePhnum='//textarea[@name="phone_constant"]', messagetext='//textarea[@class="syn-autoexpand syn-constant syn-autogrow"]',
      sendmail='//*[@id=\"accordion\"]/div[4]/ul/li[2]', SMTPIp='(//input[@class="text"])[5]',
      Port='//input[@name="port"]', Username='(//input[@name="username"])[1]',passwd='(//input[@name="password"])[1]',
      FromID='(//textarea[@name="from_constant"])[1]', ToID='(//textarea[@name="to_constant"])[1]', 
      SubID='(//textarea[@name="subject_constant"])[1]',
      msgID='(//textarea[@name="message_phrase[]"])[3]', 
      Basic='//h3[@class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all"]',
      Exit='//*[@id=\"accordion\"]/div[1]/ul/li[1]',
      ConnectorEmail='//div[@id="module-2"]//div[@class="panel-nodes-attached inner"]/div[@class="syn-node syn-node-attached-e ui-draggable syn-node-active"]',
      draggableEmail='//div[@id="module-3"]//div[@class="syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable"]',
      sms_sent_node5='//div[@id="module-2"]//div[@class="panel-nodes-attached inner"]/div[@class="syn-node syn-node-attached-w ui-draggable syn-node-active"]',
      exit_node6='//div[@id="module-4"]//div[@class="syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable"]',
      sent_email_node7 = '//div[@id="module-3"]//div[@class="panel-nodes-attached inner"]/div[@class="syn-node syn-node-attached-w ui-draggable syn-node-active"]',
      exit_node8 = '//div[@id="module-5"]//div[@class="syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable"]',
      not_Sent_Email_node9 ='//div[@id="module-3"]//div[@class="panel-nodes-attached inner"]/div[@class="syn-node syn-node-attached-e ui-draggable syn-node-active"]',
      exit_not_node10 = '//div[@id="module-6"]//div[@class="syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable"]')

